@startuml
    skinparam {
        shadowing false
        defaultFontName Mark Pro
        defaultFontColor #black
        defaultFontSize 16
        defaultFontStyle bold
        ArrowColor #red
        ArrowThickness 2
        BorderColor #red
        EntityBorderColor #red
        ParticipantBorderColor #red
    }
    skinparam sequence {
        LifeLineBorderThickness 2
        LifeLineBorderColor #black
    }

    entity "main thread" as mt #green
    entity "pool-1-thread-1" as c1 #yellow
    entity "pool-1-thread-2" as c2 #yellow
    participant "system out" as so #white

    mt -> c1 : initiate delay call
    activate c1 #blue
    mt -> c2 : initiate delay call
    activate c2 #blue

    c1 -> mt : return value 1
    deactivate c1
    mt -> so : print msg 1
    c2 -> mt : return value 2
    deactivate c2
    mt -> so : print msg 2
@enduml