@startuml
    skinparam {
        shadowing false
        defaultFontName Mark Pro
        defaultFontColor #black
        defaultFontSize 16
        defaultFontStyle bold
        ArrowColor #red
        ArrowThickness 2
        BorderColor #red
        EntityBorderColor #red
        ParticipantBorderColor #red
    }
    skinparam sequence {
        LifeLineBorderThickness 2
        LifeLineBorderColor #black
    }

    entity "main thread" as mt #green
    entity "java thread" as jt #yellow
    participant "system out" as so #white

    mt -> jt : create future 1
    mt -> jt : create future 2
    jt -> jt : complete future 1
    jt -> jt : complete future 2
    mt -> so : get future 1 and print msg
    mt -> so : get future 2 and print msg
@enduml